# spring数据库链接
server:
  port: 8024
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@//192.168.10.89:1521/his
    username: xyhis
    password: zhmz13886256909
    
    # druid配置
    druid:
      # 初始化时建立链接数量
      initial-size: 10 
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 60
      # 获取链接时最大等待时间，单位：毫秒
      max-wait: 2000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 既作为检测的间隔时间又作为test-While-Idel执行的依据
      time-between-eviction-runs-millis: 2000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      # 用来检测连接是否有效的sql 必须是一个查询语句
      validation-query: select 1 from dual
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 当数据库抛出不可恢复的异常时,抛弃该连接
      # exception-sorter:
      #   com.alibaba.druid.pool.vendor.OracleExceptionSorter
      # 是否缓存preparedStatement
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 100
      
      # 配置扩展插件
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 访问控制界面的账号密码
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        deny: 
        allow: 
        url-pattern: /druid/*
        reset-enable: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .gif,.html
  thymeleaf:
    # 模板支持，支持 HTML，XML TEXT JAVASCRIPT
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates
mybatis-plus:
  configuration:
    default-enum-type-handler: com.kaos.his.config.MybatisEnumTypeHandler
  mapper-locations:
  - classpath:mapping/**/*.xml